// AUTO-GENERATED by scripts/generate-micro-glyphs.mjs — DO NOT EDIT.
// Canonical source: design/brand/github.svg (official GitHub Invertocat).
// 8x8 alpha coverage >=128; MSB is the left pixel. Aspect ratio preserved.
export const CI_GITHUB_GLYPH_SOURCE_SHA256 = '693d7abe6f899646cc2e96856723b45e95f71885a54910b2749f6decdf7e1ee1';
export const CI_GITHUB_GLYPH_SIZE = 8;
export const CI_GITHUB_GLYPH = [60, 126, 195, 195, 195, 231, 70, 36] as const;
